name: starwave
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - python
  - scipy
  - pandas
  - matplotlib
  - numpy
  - numba
  - nb_conda
  - jupyter
  - extinction
  - pip
  - pip:
    - pyabc
    - getdist
    - torch
    - sbi
    - dill
    - corner
